motors:
  - hros_actuation_servomotor_70B3D521A020:axis2
  - hros_actuation_servomotor_70B3D521A020:axis1
  - hros_actuation_servomotor_70B3D521A016:axis1
  - hros_actuation_servomotor_70B3D521A016:axis2
  - hros_actuation_servomotor_70B3D521A03A:axis1
  - hros_actuation_servomotor_70B3D521A03A:axis2
